### ISSUE TITLE
Do we need to add version information to the monikers

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/lsif-typescript#10]

**Comment by AArnott** [comment]
The high level requirement for LSIF monikers should be that an equivalent pair of monikers exist if and only if the symbols that they label are equivalent as the developer would expect them to be. Matching runtime behavior for the application exactly is not a requirement, but if a user executes a GTD or FAR command, the results are entirely based on a moniker matching and thus monikers should be precise enough to avoid false matches but fuzzy enough to ensure the reuslts are complete.

For .NET I think we'll almost certainly _not_ want to include version info since virtually everyone will use binding redirects on .NET or ignore versions on .NET Core making type equivalence disregard assembly version at runtime. Customers will expect a reference to `MyType` from `Boo.dll` to match without regard to assembly versions of Boo.dll itself. For example, if I have a solution where project A references `Boo.dll, v2.0.0.0` and project B references `Boo.dll, v1.0.0.0` and I execute Find All References on a reference to `MyType`, I would expect to find all references across both projects A and B. This is also consistent with runtime behavior if we assume these projects contribute to the same application which has a binding redirect unifying these two types.

For other languages to deviate from this and include version info in the moniker, I'd be interested in hearing the case why we should _not_ consider a symbol to be equivalent across versions.

On the other hand, we _should_ have version information as precisely as we can get it, from the package and the assembly (where applicable), in the LSIF for all imported libraries so that we can have GTD jump across repos.

**Comment by jdneo** [comment]
Considering the scenario of GTD jump across repos, just as @AArnott has said, the monikers should contain version information to make sure it will point to the right place in another repo as precise as possible.

**Comment by dbaeumer** [comment]
The new format has a package information vertex which can carry a version identifier.
