### ISSUE TITLE
Do we need to define the basic structure of the monikers

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/lsif-typescript#11]
The current monikers use `:` as a separation character which could be a valid file name character (at least under Linux and macOS). So we need to spec this and escape in a file name.

**Comment by AArnott** [comment]
If monikers are opaque strings, we shouldn't disallow any character IMO. Let the spec for an individual language's moniker spec this out so that any LSIF implementation for a given language will produce equivalent monikers.

If they are not opaque strings, then their formatting should reuse an existing spec (e.g. JSON) and follow whatever rules that requires.

**Comment by dbaeumer** [comment]
@AArnott came to the same conculsion while implementing an improved moniker support for project references. Here is what I am landed on based on feedback from C#

- a moniker has a schema
- a moniker has an identifier. This is opaque. Only the language that provides it needs to encode and if necessary decode it.

**Comment by dbaeumer** [comment]
Closing. Is covered with the new moniker vertex.
