### ISSUE TITLE
Edge before vertex is seen

### ISSUE THREAD

**Issue by homitc** [Microsoft/lsif-typescript#15]
When I use the tool on [vsls-guestbook](https://github.com/lostintangent/vsls-guestbook/) commit# b93232d95da96cb39744151914f9de869358e763, there's an issue where vertex 422 is referenced by edge 610 before it is output.
![image](https://user-images.githubusercontent.com/43962277/50242147-4c288f80-037e-11e9-9a0b-ab4726aa35a8.png)
![image](https://user-images.githubusercontent.com/43962277/50242162-5ba7d880-037e-11e9-830c-1ed136b9e258.png)
![image](https://user-images.githubusercontent.com/43962277/50242835-5186d980-0380-11e9-9574-2eaa6bd0f324.png)

610 is the only edge that outputs too early, everthing else including other edges to and from 422 work.

**Comment by derekbekoe** [comment]
Seeing the same issue while running the lsif tool (`tsc-lsif`) on https://github.com/lostintangent/vsls-guestbook/pull/11/commits/b93232d95da96cb39744151914f9de869358e763

```
...
{"id":513,"type":"edge","label":"textDocument/references","outV":511,"inV":312},
...
{"id":312,"type":"vertex","label":"referenceResult","declarations":[314],"definitions":[],"references":[508]},
```

The edge with id 513 appears in the file before the vertex with id 312.

This is the command used to run the lsif tool:
```
node .\main.js --outputFormat=json -p ...\vsls-guestbook\jsconfig.json > lsif-out.json
```

This leads to Find All References returning a single result instead of the expected two results.

Here is the full output from the tool:
https://gist.github.com/derekbekoe/8a9a317625eba264df708b66a904feef

**Comment by LukaszMendakiewicz** [comment]
Actually, does the specification stipulate anywhere that emitting an edge before a vertex is not legal? I could not find any mention of that, and there are formats like GraphViz where this is (or at least seems to be) legal. If we intend to make this a requirement, then this needs to be stated as such.

**Comment by dbaeumer** [comment]
@LukaszMendakiewicz I think it makes transforming this into a DB easier. I will make sure that the spec will mention this. Objections?
