### ISSUE TITLE
Declarations being treated as definitions

### ISSUE THREAD

**Issue by jumattos** [Microsoft/lsif-typescript#18]
Consider the following typescript code snippet:

```
interface Person {
    walk(): void;
}

class Student implements Person {
    walk(): void {
        console.log("Student walking...");
    }
}
```

Person.walk (line 2) is being recorded by the tool as a definition, although it doesn't have an implementation:

```
{
    "id": 22,
    "type": "vertex",
    "label": "range",
    "start": {
        "line": 1,
        "character": 4
    },
    "end": {
        "line": 1,
        "character": 8
    },
    "tag": {
        "type": "definition",
        "text": "walk",
        "kind": 7,
        "fullRange": {
            "start": "@{line=1; character=4}",
            "end": "@{line=1; character=17}"
        }
    }
}
```

This can be particularly troublesome for goto implementation, since it depends on differentiating between definitions and declarations (a declaration cannot be an implementation).

I believe the issue is related to the `initializeDeclarations` function and propose a check for implementation body before assigning the type of the vertex.

**Comment by dbaeumer** [comment]
Actually this is interesting: the TS language server doesn't make any difference between declarations and definitions. There is also no `Goto Declaration` only `Goto Definition` when executed on something like `p.walk()`. The only case where the differentiation would make sense is a `*.d.ts` file where the definition lives in a JS file. But the TS server has not support for that either. 

We can still tag this as a declaration, however the tsc lsif code should never make any decision based on the tag. It should always use the underlying TS symbol which tells the truth at the end. 

I am not sure I understand why this is troublesome for `Goto Implementation` since it is a result set anyways and what we put in there should not depend on these tags. 

Can you explain this a little ?

**Comment by jumattos** [comment]
Thank you for explaining, I did not know there was no `Goto Declaration` in Typescript.

In this case, if we `Goto Implementation` on `Person.walk()`, we should only get `Student.walk()` as a result. However, we are passing `Person.walk()` to `recordDeclaration`, since we don't differentiate between definitions and declarations. In turn, since I add all declarations to implementation results, we have `Person.walk()` as part of the results, which is not correct.

A solution would be to check for a body before adding the definition/declaration to implementation results. Another would be treating them separately, even though TS makes no distinction.

**Comment by dbaeumer** [comment]
I would for now check if the declaration is in an interface and  if so ignore it. I don't know what side effects it will have it we start to distinguish between declaration and definition in TS. Needs some careful thinking. I opened https://github.com/Microsoft/lsif-typescript/issues/19

**Comment by jumattos** [comment]
Thanks for opening the issue, I will close this one for now. I will be working on a fix for that specific situation and push the changes to my open PR.
